### ISSUE TITLE
pc.utils ----- ImportError

### ISSUE THREAD

**Issue by XGuider** [yanx27/Pointnet_Pointnet2_pytorch#10]
Thank you for your good work！
i want view shapenet dataset,but i run to get next.......
`    from data_utils.ShapeNetDataLoader import load_data
ImportError: cannot import name 'load_data'
`

**Comment by ZJU-PLP** [comment]
> Thank you for your good work！
> i want view shapenet dataset,but i run to get next.......
> ` from data_utils.ShapeNetDataLoader import load_data ImportError: cannot import name 'load_data'`

I also meet the problem now. Could you mind telling me your final method for this problem?

**Comment by ZJU-PLP** [comment]
> Thank you for your good work！
> i want view shapenet dataset,but i run to get next.......
> ` from data_utils.ShapeNetDataLoader import load_data ImportError: cannot import name 'load_data'`

@XGuider I also meet the problem now. Could you mind telling me your final method for this problem?

**Comment by XGuider** [comment]
maybe you can use other dataset to test,our dataset hava error
