### ISSUE TITLE
Why need vote when test part segmentation?

### ISSUE THREAD

**Issue by TangToy** [yanx27/Pointnet_Pointnet2_pytorch#101]
In test_partseg.py, line 108:
`            for _ in range(args.num_votes):
                seg_pred, _ = classifier(points, to_categorical(label, num_classes))
                vote_pool += seg_pred`
The seg_pred for each vote is the same, why it needs to vote args.num_votes times?  Is it enough to implement the inference process only once? Thanks.

**Comment by yanx27** [comment]
@TangToy  It follows the protocol of official PointNet++. Actually, voting is used to eliminate the randomness during the testing. If you use data augmentation before feeding data in the network, it will introduce randomness for the results.

**Comment by TangToy** [comment]
Thanks. I found that every time when points are fed into the pointnet++, the points will be grouped several times. For each grouping, the points need to be farthest-sampling first. The first centroid in _farthest_point_sample_ function is chosen randomly, so each vote process could result different results. For the pointnet, each vote process can result in the same results.
