### ISSUE TITLE
Can I get the best_model.pth of PointNet2_SSG (Pytorch without normal) or PointNet (Pytorch without normal)?

### ISSUE THREAD

**Issue by ChenWenming1995** [yanx27/Pointnet_Pointnet2_pytorch#102]
Hi!

Thanks for your work!

I need these models without normals and they are not available here now. Can you push it to Git?

Thanks:)

**Comment by ChenWenming1995** [comment]
thanks:)

**Comment by ChenWenming1995** [comment]
Sorry to bother you again.

Can you release the PointNet (Pytorch without normal)?

Thanks a lot:)

**Comment by Dlemand** [comment]
sorry for disturb,well,i cannot load the pth file by the command torch.load()。 may the files broken?
