### ISSUE TITLE
ShapeNetDataLoader.py 变量名拼写错误

### ISSUE THREAD

**Issue by hfun2017** [yanx27/Pointnet_Pointnet2_pytorch#105]
https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/bba1f6156371fbabf02bf4c47062dfde21a32b46/data_utils/ShapeNetDataLoader.py#L91

变量ppoint_set ,拼写错误，造成105行报错，找不到变量point_set
        point_set[:, 0:3] = pc_normalize(point_set[:, 0:3])

**Comment by yanx27** [comment]
Thx, already fixed
