### ISSUE TITLE
Features meaning of the S3DIS dataset 

### ISSUE THREAD

**Issue by huangchaoxing** [yanx27/Pointnet_Pointnet2_pytorch#11]
Hi,
I noticed that the input to the semantic segmentation network has 9 dimensional features. Apart from xyz coordinate and normal, what is the feature meaning of the rest 3 dimensions. Is it RGB ?
Thank you 
Cheers

**Comment by ZJU-PLP** [comment]
> Hi,
> I noticed that the input to the semantic segmentation network has 9 dimensional features. Apart from xyz coordinate and normal, what is the feature meaning of the rest 3 dimensions. Is it RGB ?
> Thank you
> Cheers

9 dimensional features are ayx,normal feature and RGB feature!

**Comment by yanx27** [comment]
They are xyz, RGB and normalized XYZ.
