### ISSUE TITLE
How to visualize the result of ShapeNet train?

### ISSUE THREAD

**Issue by ch19971118** [yanx27/Pointnet_Pointnet2_pytorch#114]
How to visualize the result of ShapeNet train?

**Comment by yanx27** [comment]
@ch19971118 please use codes [here](https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/master/visualizer/show3d_balls.py).

**Comment by ch19971118** [comment]
> @ch19971118 please use codes [here](https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/master/visualizer/show3d_balls.py).

Thank you
