### ISSUE TITLE
About point_idxs.size in S3DISDataLoader

### ISSUE THREAD

**Issue by Liu-Feng** [yanx27/Pointnet_Pointnet2_pytorch#116]
Thanks for your awesome project!
I have some doubts about the point_index.size in Line 59-60 in S3DISDataLoader. Why break the loop while the size is larger than 1024, According the protocol of S3DIS, it might shoud break while the size is larger than 4096( the point number).

Have a nice day!
Looking foreard to you reply!

**Comment by yanx27** [comment]
@Liu-Feng Hi, this operation just constraint the minimal point's number in the cube, and 4096 is the max point number feed in the network.
