### ISSUE TITLE
View segmentation result

### ISSUE THREAD

**Issue by lakshmipriya369** [yanx27/Pointnet_Pointnet2_pytorch#117]
How do we view the predicted output for segmentation? I wish to view the output with point cloud labeled based on prediction.

**Comment by yanx27** [comment]
Hi @lakshmipriya369 , you can use `--visual` config in `python test_semseg.py` and visualization results will save in `log/sem_seg/xxx/visual/`. Thus, you can visualize these `.obj` file by MeshLab.

**Comment by lakshmipriya369** [comment]
Does this apply to test_partseg.py as well? I should have mentioned earlier that it about Part Segmentation.

**Comment by yanx27** [comment]
@lakshmipriya369 Hi, visualization for part segmentation currently is not supported, you can modify `Pointnet_Pointnet2_pytorch/visualizer/show3d_balls.py` to show the saved results.

**Comment by lakshmipriya369** [comment]
@yanx27 Thanks for the info. Also I wasnt able to get the output models saved after running test_partseg.py. I only got the IOUs and accuracies. Which folder contains the saved results?

**Comment by Sinerei** [comment]
I have the same problem! 
I would be grateful if you could give us the correct saved results path.

**Comment by jiezi1678458785** [comment]
Hello, I have the same problem!
I wonder how to use "--visual" config in python test_semseg.py, is it simply add " parser.add_argument('--visual', action='store_true', default=False, help='visualize result [default: False]')" into train_partseg.py?
