### ISSUE TITLE
is there a script only to test the model?

### ISSUE THREAD

**Issue by sheshap** [yanx27/Pointnet_Pointnet2_pytorch#13]
I have trained pointnet++ using below command.
python train_partseg.py --model_name pointnet2

I see it also gives the test accuracies after each epoch and the final best test accuracy.

Now if I have to only test the accuracy again, how can I do it?

**Comment by lixincheng4026** [comment]
you can write a script based on ./utils.test, but when i do that, i found the accuracy has dropped a lot. Really dont know the reason
