### ISSUE TITLE
How can I predict all points？

### ISSUE THREAD

**Issue by zhoujinhai** [yanx27/Pointnet_Pointnet2_pytorch#132]
I want to segment my own point cloud data，the amount of these data is not uniform. For example, some have 4200 points, some 8500 points, and some 9000 or more. If I set npoints and the segmentation result has only npoints, how can I predict all the points.

**Comment by AlexHex7** [comment]
@zhoujinhai  Hi, How to predict all points, finnaly?

**Comment by zhoujinhai** [comment]
> @zhoujinhai Hi, How to predict all points, finnaly?

The inputs N is variable，so you can take all points as input!

**Comment by YOLO-study-del** [comment]
Hello! You said that if I want to predict all points, I can change the npoints. But the value is the max number of my points or every time I want to predict one scene, I should change the value of npoints?
