### ISSUE TITLE
Hi Is there a way to display the outputs after the training is completed on the S3DIS dataset 

### ISSUE THREAD

**Issue by jorgegarcia197** [yanx27/Pointnet_Pointnet2_pytorch#14]

**Comment by jorgegarcia197** [comment]
I was trying to see throughout the whole repo to see where the output or the final segmentated dataset is saved, but instead only the model where I believe only the weights are stored are saved.

**Comment by arunumd** [comment]
Even I have the same question. The repository does not seem to have any way to visualize the results of segmentation.
