### ISSUE TITLE
请问 vote投票的作用是什么？

### ISSUE THREAD

**Issue by yezi1996** [yanx27/Pointnet_Pointnet2_pytorch#142]
parser.add_argument('--num_votes', type=int, default=3, help='aggregate segmentation scores with voting [default: 5]')
请问 vote投票的作用是什么？ 论文中没有提到vote，所以看不懂，真的非常非常急，请教一下，非常感谢！

**Comment by yanx27** [comment]
It averages multiple predictions and makes final results more stable.

**Comment by yezi1996** [comment]
如果我只想预测一次就作为结果，是不是应该将num_votes的值设置为1？

**Comment by yezi1996** [comment]
ok，i have already understood，thanks very much。 ^v^
