### ISSUE TITLE
关于语义分割中iou交并比的计算公式的问题

### ISSUE THREAD

**Issue by yezi1996** [yanx27/Pointnet_Pointnet2_pytorch#146]
total_seen_class_tmp[l] += np.sum((whole_scene_label == l))
total_correct_class_tmp[l] += np.sum((pred_label == l) & (whole_scene_label == l))
total_iou_deno_class_tmp[l] += np.sum(((pred_label == l) | (whole_scene_label == l)))
您好，在代码里面iou的计算公式如下，
iou_map = np.array(total_correct_class_tmp) / (np.array(total_iou_deno_class_tmp, dtype=np.float) + 1e-6)
但是，我觉得应该是
iou_map = np.array(total_correct_class_tmp) / ((np.array(total_iou_deno_class_tmp, dtype=np.float) - np.array(total_correct_class_tmp) ) + 1e-6)
在计算iou交并比时，交并比中的“并”是否应该要减去公共部分？

**Comment by LeeHiking** [comment]
使用的是或运算，因此没有重复计算公共部分

**Comment by yezi1996** [comment]
我懂了，因为或运算是会短路的，谢谢！！！
