### ISSUE TITLE
关于每个房间的miou计算的问题

### ISSUE THREAD

**Issue by yezi1996** [yanx27/Pointnet_Pointnet2_pytorch#148]
iou_map = np.array(total_correct_class_tmp) / (np.array(total_iou_deno_class_tmp, dtype=np.float) + 1e-6)
arr = np.array(total_seen_class_tmp)
tmp_iou = np.mean(iou_map[arr != 0])
---------------------------------------------
为什么这里是tmp_iou = np.mean(iou_map[arr != 0]) ，而不是  tmp_iou = np.mean(iou_map) ？  有人能解答一下嘛，非常感谢！！！

**Comment by yezi1996** [comment]
最终计算整个Area5的miou时，
IoU = np.array(total_correct_class) / (np.array(total_iou_deno_class, dtype=np.float) + 1e-6)
log_string('eval point avg class IoU: %f' % np.mean(IoU))
却没有使用 np.mean(IoU[arr != 0])，这是为什么呢？

**Comment by yanx27** [comment]
这是因为在计算单个房间的时候，有些房间没有出现某个类别的点，因此在平均的时候将它们忽略。但是在计算所有的房间的时候不会出现这样的问题。
