### ISSUE TITLE
test Pointnet2 network

### ISSUE THREAD

**Issue by zhangshabao** [yanx27/Pointnet_Pointnet2_pytorch#15]
I want to use your code to test Pointnet2 network, at this point I input data as point cloud file, its format as [1,3,2048].It appear error:"\model\pointnet_util.py", line 79, in farthest_point_sample   centroid = xyz[batch_indices, farthest, :].view( B, 1, 3) RuntimeError: shape '[1, 1, 3]' is invalid for input of size 2047.

**Comment by alfredtorres** [comment]
I come to this problem too.  I solve this problem by transpose the data. I think the input shape should be [1, 2048, 3]. Hope to help you
