### ISSUE TITLE
Inference/prediction for unlabeled data?

### ISSUE THREAD

**Issue by AI-Hunter** [yanx27/Pointnet_Pointnet2_pytorch#156]
@yushiangw 
Thanks for nice repo. your prediction code use label data. The label information is used also in add_vote() function.
How can I use the prediction code for unlabeled data?
Thanks again for your repo

**Comment by madinwei** [comment]
@AI-Hunter , hello, have you been able to use prediction on new data? if so. would you mind share with me or giving me any advice on how to do it? thank you in advance.
