### ISSUE TITLE
Have someone tried "train_classification.py" with customed dataset?

### ISSUE THREAD

**Issue by yuhan1010** [yanx27/Pointnet_Pointnet2_pytorch#160]
I am working on my final year project, and I need to deliver my own training data on pointnet2 to recognize specific objects. However, I am stucking on training data. Of course, I have same formats with data in ModelNet10/40.

Could someone give me a favor? thx

**Comment by tjdqja218** [comment]
hi,
Did you solve the problem?
I made my own dataset in .txt format(consists of X,Y,Z) 
But, when I run "train_classification.py", key errors occur.
(I ran the code with "--use_normals" following the comments in [here](https://github.com/yanx27/Pointnet_Pointnet2_pytorch/issues/70))

if you solved your problem, could you give me the solution?

**Comment by 13717630148** [comment]
> hi, Did you solve the problem? I made my own dataset in .txt format(consists of X,Y,Z) But, when I run "train_classification.py", key errors occur. (I ran the code with "--use_normals" following the comments in [here](https://github.com/yanx27/Pointnet_Pointnet2_pytorch/issues/70))
> 
> if you solved your problem, could you give me the solution?

hello, have you solved the question? Can we train the model with custom data (consisting only of xyz)
