### ISSUE TITLE
ImportError: No module named data_utils.ModelNetDataLoader

### ISSUE THREAD

**Issue by hengliangzhu** [yanx27/Pointnet_Pointnet2_pytorch#17]
Thank you for your good work！
But when training，i get some errors:
Traceback (most recent call last):
  File "train_clf.py", line 14, in <module>
    from data_utils.ModelNetDataLoader import ModelNetDataLoader, load_data
ImportError: No module named data_utils.ModelNetDataLoader
I don't know what's the problem and can you kindly tell me how to solve it?

**Comment by sheshappanavar** [comment]
Please create an empty __init__.py file inside the data_utils folder

P.S: Also create one inside models directory

**Comment by hengliangzhu** [comment]
Many thanks
