### ISSUE TITLE
Cannot download alignment ModelNet

### ISSUE THREAD

**Issue by Vishak66** [yanx27/Pointnet_Pointnet2_pytorch#174]
Hi,

The link that is provided to download the alignment ModelMet does not seem to work. If i download from the Princeton website, the ModelNet is in .off format. Anyone else face the same issue and any suggestions to fix this is greatly appreciated.

**Comment by Dioxane123** [comment]
Hi,

I found the same problem. Others said I can download the dataset by "wget https://shapenet.cs.stanford.edu/media/modelnet40_normal_resampled.zip --no-check-certificate" ,but it still not worked on me. If I didn't use the proxy, it said connected timeout. If I use the proxy, it said “TLS connection terminated abnormally”.

Did you solve the problem? Any suggestion is valuable. Thank you again.
