### ISSUE TITLE
can not reach 89.4 on pointnet classfication

### ISSUE THREAD

**Issue by lixincheng4026** [yanx27/Pointnet_Pointnet2_pytorch#18]
I runned the code on modelnet40 with ubuntu16.04 pytorch1.1 and a 1070. But I can't get the score that you report, I get only 88.5. Is that the dataset problem, because I used the dataset that automatically downloaded  by the official Pointnet code which is 416M instead of the dataset you provided which is 1.9G. Or is the effect of input transform or feature transform. By the way my batchsize is 24. Really dont know where is the problem.

**Comment by XGuider** [comment]
hi，i train runned the code on modelnet40 ,i get only 10 best.Have you changed anything? @lixincheng4026
