### ISSUE TITLE
What is the difference between 'PointNet2PartSeg' and 'PointNet2SemSeg'?

### ISSUE THREAD

**Issue by cherry-ing** [yanx27/Pointnet_Pointnet2_pytorch#2]
Hi @yanx27 ! Thank you for your work!
There are two classes relating to segmentation, can they both be used for segmentation task?
I find that you only use class `PointNet2PartSeg` in `train_seg.py`.

**Comment by yanx27** [comment]
> Hi @yanx27 ! Thank you for your work!
> There are two classes relating to segmentation, can they both be used for segmentation task?
> I find that you only use class `PointNet2PartSeg` in `train_seg.py`.

Thank you for you attention, 'PointNet2PartSeg' and 'PointNet2SemSeg' use different dataset, you can try  ScanNet dataset with PointNet2SemSeg . I will complete this part in future :)
