### ISSUE TITLE
when i use my custom data the pointnet2_part_seg_msg model is not accepting my input feature 

### ISSUE THREAD

**Issue by madinwei** [yanx27/Pointnet_Pointnet2_pytorch#218]
Hello, @lly007 @yushiangw @yanx27 @tarmas99 .
thank you for this awesome pointnet2 code. 

I have built and labeled my data according to the shapnet scheme. but I only have one class and three parts. I have modified the train_parseg.py to read and load my data, I also change the ShapeNetDataLoader.py to accustom to my data one class and three parts.

However, I didn't understand how to solve this issue. if possible can you provide any insight or help in the matter?
```
new_points = F.relu(bn(conv(new_points)))
  File "/home/mad/Pointnet_Pointnet2_pytorch-master/models/pointnet2_part_seg_msg.py", line 44, in forward
    l0_points = self.fp1(l0_xyz, l1_xyz, torch.cat([cls_label_one_hot,l0_xyz,l0_points],1), l1_points)
  File "/home/mad/Pointnet_Pointnet2_pytorch-master/train_partseg2.py", line 190, in main
    seg_pred, trans_feat = classifier(points, to_categorical(label, num_classes))
  File "/home/mad/Pointnet_Pointnet2_pytorch-master/train_partseg2.py", line 302, in <module>
    main(args)
RuntimeError: Given groups=1, weight of size [128, 150, 1], expected input[16, 135, 10048] to have 150 channels, but got 135 channels instead
```

Thank you in advance.

**Comment by marcofariasmx** [comment]
@madinwei how were you able to solve this?

**Comment by madinwei** [comment]
> @madinwei how were you able to solve this?

HI @marcofariasmx , unfortunately, I moved to another project, and I have deleted my pointnet project. I don't recall what I did to this issue. but if I have free time, I will try to download and run this repository on my data.

**Comment by marcofariasmx** [comment]
> > @madinwei how were you able to solve this?
> 
> HI @marcofariasmx , unfortunately, I moved to another project, and I have deleted my pointnet project. I don't recall what I did to this issue. but if I have free time, I will try to download and run this repository on my data.

Hello @madinwei thank you for getting back at me. No need to revise it, I was able to solve it by following this thread https://github.com/yanx27/Pointnet_Pointnet2_pytorch/issues/71 but thank you anyways for the offered help!
