### ISSUE TITLE
Why does the code use Conv1d of 1*1 kernel_size, but the paper uses MLP

### ISSUE THREAD

**Issue by dewjiguang** [yanx27/Pointnet_Pointnet2_pytorch#219]
![image](https://user-images.githubusercontent.com/41632105/221454900-7940e521-f9f8-49d2-982f-1115e3f33c67.png)
![image](https://user-images.githubusercontent.com/41632105/221455126-6510fca4-9aca-45b0-8290-f30b84859b93.png)

In model/pointNet_sem_seg.py, we can see code use Conv1d of 1*1 kernel_size, but the paper uses MLP.
Does it means Conv1d of 1*1 kernel_size is equal to MLP?
Thanks

**Comment by liuxuexun** [comment]
1*1 convolution compute in the feature dimention and it is equal to linear

**Comment by rayryeng** [comment]
It is known that using a 1 x 1 convolution is equivalent to using a MLP: https://stackoverflow.com/questions/39366271/for-what-reason-convolution-1x1-is-used-in-deep-neural-networks

**Comment by dewjiguang** [comment]
> It is known that using a 1 x 1 convolution is equivalent to using a MLP: https://stackoverflow.com/questions/39366271/for-what-reason-convolution-1x1-is-used-in-deep-neural-networks

thanks you,i have got it

**Comment by dewjiguang** [comment]
i write a blog about this issue:
https://blog.csdn.net/php_thebest_language/article/details/129264392
