### ISSUE TITLE
How to comprehend the function "index_points"

### ISSUE THREAD

**Issue by liuxuexun** [yanx27/Pointnet_Pointnet2_pytorch#220]
Thanks for your excellent reimplement in Pytorch.

In this [function,](https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/eb64fe0b4c24055559cea26299cb485dcb43d8dd/models/pointnet2_utils.py#L59) the code `new_points = points[batch_indices, idx, :]` is a bit difficult for me to understand.

Is it some thing different or the same with three interpolate? Because I see the original code use three interpolate here.

And why it can work similar with the three interpolate function?

```
def index_points(points, idx):
    """

    Input:
        points: input points data, [B, N, C]
        idx: sample index data, [B, S]
    Return:
        new_points:, indexed points data, [B, S, C]
    """
    device = points.device
    B = points.shape[0]
    view_shape = list(idx.shape)
    view_shape[1:] = [1] * (len(view_shape) - 1)
    repeat_shape = list(idx.shape)
    repeat_shape[0] = 1
    batch_indices = torch.arange(B, dtype=torch.long).to(device).view(view_shape).repeat(repeat_shape)
    new_points = points[batch_indices, idx, :]
    return new_points
```

**Comment by Jonnoy-Gates** [comment]
Hi, mellody.  Actually `new_points = points[batch_indices, idx, :]` is like *slicing the array from two dimensions*. In this case, `batch_indices` and `idx` has the same size [B, S], and `batch_indices` are actually represented as the expression 
tensor([[0, 0, 0, 0,...],
        [1, 1, 1, 1,...],...,
        [B-1, B-1, B-1, B-1,...]])
So after slicing `points`, we get `new_points` with Size([B, S, C]) which means every idx_points with `idx` has been extraced from source-`points`. 
You can get more detailed information in this Chinese blog [Pointnet++代码详解（四）：index_points函数](https://blog.csdn.net/weixin_42707080/article/details/105303674)

**Comment by liuxuexun** [comment]
> Hi, mellody. Actually `new_points = points[batch_indices, idx, :]` is like _slicing the array from two dimensions_. In this case, `batch_indices` and `idx` has the same size [B, S], and `batch_indices` are actually represented as the expression tensor([[0, 0, 0, 0,...], [1, 1, 1, 1,...],..., [B-1, B-1, B-1, B-1,...]]) So after slicing `points`, we get `new_points` with Size([B, S, C]) which means every idx_points with `idx` has been extraced from source-`points`. You can get more detailed information in this Chinese blog [Pointnet++代码详解（四）：index_points函数](https://blog.csdn.net/weixin_42707080/article/details/105303674)

ok, thank you, it is really helpful.

**Comment by mikkelmedm** [comment]
Sorry to reopen.
Am curious how this interpolate method compares to the original three_interpolate method, used [here](https://github.com/charlesq34/pointnet2/blob/42926632a3c33461aebfbee2d829098b30a23aaa/tf_ops/3d_interpolation/tf_interpolate.py#L7)?
