### ISSUE TITLE
缺少eval.tet

### ISSUE THREAD

**Issue by kk518** [yanx27/Pointnet_Pointnet2_pytorch#223]
![image](https://user-images.githubusercontent.com/50757822/225524084-c82cbc65-6dd5-4aaf-a658-5e6af0c0283d.png)

 为什么会缺少这个文件

**Comment by zhengaurora** [comment]
解决了么？

**Comment by apalapramanik** [comment]
same problem!! Did you solve?

**Comment by Lzl0925** [comment]
解决了吗

**Comment by 13717630148** [comment]
same problem @yanx27

**Comment by WanderingSta** [comment]
解决了吗？怎么解决的

**Comment by kk518** [comment]
自己代码拉下来debug解决就行了

**Comment by WanderingSta** [comment]
咋解决的，我是用python test_classification.py --log_dir pointnet2_cls_ssg这行命令
![image](https://github.com/user-attachments/assets/cad53ef0-d3ef-4f53-aa87-da2f0c68fe8c)

**Comment by WanderingSta** [comment]
> 自己代码拉下来debug解决就行了

能详细说说不

**Comment by WanderingSta** [comment]
能详细说说不


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yanx27/Pointnet_Pointnet2_pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月25日(星期一) 下午3:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yanx27/Pointnet_Pointnet2_pytorch] 缺少eval.tet (Issue #223)





 
自己代码拉下来debug解决就行了

**Comment by kk518** [comment]
> 咋解决的，我是用python test_classification.py --log_dir pointnet2_cls_ssg这行命令 ![image](https://private-user-images.githubusercontent.com/112313941/389416297-cad53ef0-d3ef-4f53-aa87-da2f0c68fe8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MjA3ODEsIm5iZiI6MTczMjUyMDQ4MSwicGF0aCI6Ii8xMTIzMTM5NDEvMzg5NDE2Mjk3LWNhZDUzZWYwLWQzZWYtNGY1My1hYTg3LWRhMmYwYzY4ZmU4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQwNzQxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWQ3Y2RjOTNiMzMzNWI5NWMwMWQ4MjYzNDlkZTE5MjYwN2Q3MGNmY2RkYjE3YzJjMjY3ZmUzNGI3YWIzMzBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.U5Cny9YKQ_l7ZOave9EZzIJ9xQzvsqexeMZoFfXJFQw)

别直接用命令 代码拉下来 debug看缺什么改一下就行了
