### ISSUE TITLE
How to visualize the sementic segmentation results of S3DIS dataset?

### ISSUE THREAD

**Issue by limt15** [yanx27/Pointnet_Pointnet2_pytorch#24]
Dear author, thank you for sharing the code.
How to visualize the sementic segmentation results of S3DIS dataset?
Could you provide some suggestion for me ?

**Comment by neverstoplearn** [comment]
i have meet the same problem have you solve it? thanks.

**Comment by malcolmyanguci** [comment]
I use rviz from ROS package or meshlab to visualize it. Both of them can handle the large set of pointcloud.  Recently I found the pptk can visualize 3D pointcloud too, but i haven't try it in a large set of pointcloud. Please let me know if you try pptk and how is the experience.
Here is the link of pptk
[https://developer.here.com/blog/interactive-visualization-of-10m-3d-points-with-new-open-source-python-package-pptk](url)

**Comment by cookie54sun** [comment]
Excuse me，how long will it take to train S3DIS dataset? Due to 6-fold cross-validation, I worry it will take a long time. Thanks!
