### ISSUE TITLE
wrong label loss in PointNetLoss

### ISSUE THREAD

**Issue by BlurryLight** [yanx27/Pointnet_Pointnet2_pytorch#30]
https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/31deedb10b85ec30178df57a6389b2f326f7c970/model/pointnet.py#L242

`nll_loss` is used but the input `labels_pred` from here is not a `log_softmax`, causing a negative `label loss` value.
https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/31deedb10b85ec30178df57a6389b2f326f7c970/model/pointnet.py#L209

Either using a `log_softmax` before `nll_loss` or change the  `nll_loss` to `cross_entropy` can solve it.

**Comment by amiltonwong** [comment]
I think `nll_loss` already does the work. No need to append `log_softmax`. No negative label loss value will be created. You can check the actual value though.

**Comment by BlurryLight** [comment]
@amiltonwong  Since the code has been completely refactored , this issue should be closed.
