### ISSUE TITLE
Why transpose points shape before tranining?

### ISSUE THREAD

**Issue by Salingo** [yanx27/Pointnet_Pointnet2_pytorch#31]
Hello,
Thanks for your great work!
I have a small question that why you switch the 2nd and 3rd channel of the input points during training? (e.g. line 161 in [train_cls.py](https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/6dd9e5c20975badc6e1e153bbde15e52292cff68/train_cls.py#L161))

**Comment by BlurryLight** [comment]
since `nn.Conv1d` requires  (B, C, N) input where B is the batchsize, C is the point xyz (with feature) and N is the number of points while the Dataloader provides (B,N,C) shape of points.

**Comment by Salingo** [comment]
@BlurryLight Thank you! I am new to PyTorch, now I realized :D
