### ISSUE TITLE
PointNet2 Part Seg point coordinates considered twice, once in l0_points and once in l0_xyz. Is it done on purpose to increase the accuracy?

### ISSUE THREAD

**Issue by ruc98** [yanx27/Pointnet_Pointnet2_pytorch#32]
`def forward(self, xyz, cls_label):

        # Set Abstraction layers

        B,C,N = xyz.shape

        if self.normal_channel:

            l0_points = xyz

            l0_xyz = xyz[:,:3,:]
  
      else:
  
          l0_points = xyz
  
          l0_xyz = xyz
`

In here, why dose l0_point include the poiition vector as well? Should'nt it be 3 for normal and None otherwise?

**Comment by yanx27** [comment]
> `def forward(self, xyz, cls_label):
> 
> ```
>     # Set Abstraction layers
> 
>     B,C,N = xyz.shape
> 
>     if self.normal_channel:
> 
>         l0_points = xyz
> 
>         l0_xyz = xyz[:,:3,:]
> 
>   else:
> 
>       l0_points = xyz
> 
>       l0_xyz = xyz
> ```
> 
> `
> 
> In here, why dose l0_point include the poiition vector as well? Should'nt it be 3 for normal and None otherwise?

Thank you for your attention!  I use both group normalized coordinates and their original coordinates to update their features, which may slightly increase the performance.  You can try 'None' like the official PointNet++ and see what happens :)

**Comment by ruc98** [comment]
Sure will try that. 
But the PointNetSetAbstractionMsg layer is already concatenating xyz and points. This will create grouped_points to have xyz+xyz+features as the total features. Is it what you desire to do?

**Comment by yanx27** [comment]
> Sure will try that.
> But the `PointNetSetAbstractionMsg` layer is already concatenating xyz and points. This will create grouped_points to have xyz+xyz+features as the total features. Is it what you desire to do?

Group point will have grouped_xyz+xyz+features as total features and you can notice that `grouped_xyz -= new_xyz.view(B, S, 1, C)` in line 244, which is not same with xyz :)

**Comment by ruc98** [comment]
Yes, now I understand. Thanks a lot.
Your code is very clean and organized compared to the original paper implementation.
