### ISSUE TITLE
Diffrences between utils of pyotrch version and cuda version

### ISSUE THREAD

**Issue by GalaxyWM** [yanx27/Pointnet_Pointnet2_pytorch#33]
@yanx27 thanks for your work!
are there any differences between tf_utils (such as FPS, ballquery) of pytorch version and cuda version

**Comment by yanx27** [comment]
> @yanx27 thanks for your work!
> are there any differences between tf_utils (such as FPS, ballquery) of pytorch version and cuda version

There is no difference in algorithm implementation, but CUDA version should be faster :)
