### ISSUE TITLE
Error while copying batch data to cuda tensor in test_semseg.py 

### ISSUE THREAD

**Issue by ashj9** [yanx27/Pointnet_Pointnet2_pytorch#34]
@yanx27 Thanks for this very useful repo.
Im trying to use test code for semantic segmentation in test_semseg.py. 
For the following block:
  
![image](https://user-images.githubusercontent.com/32778419/70388158-2142ab80-19d4-11ea-9a92-10a1c4df19c2.png)

I am getting below error:
`
Traceback (most recent call last):
  File "test_semseg.py", line 204, in <module>
    main(args)
  File "test_semseg.py", line 133, in main
    batch_data[0:real_batch_size, ...] = scene_data[start_idx:end_idx, ...]
TypeError: can't assign a numpy.ndarray to a Variable[CUDAType]
`

I could see that because within the for loop, once the variable **batch_data** has been converted to cuda tensor in the very first iteration of for loop, I believe the same cuda tesnor is being assing with new set of block data via **scene_data[start_idx:end_idx, ...]** which is still a numpy array. Could you please confirm if my understanding about the error is correct. I can rewrite the loop accordingly.
TIA

**Comment by yanx27** [comment]
> @yanx27 Thanks for this very useful repo.
> Im trying to use test code for semantic segmentation in test_semseg.py.
> For the following block:
> 
> ![image](https://user-images.githubusercontent.com/32778419/70388158-2142ab80-19d4-11ea-9a92-10a1c4df19c2.png)
> 
> I am getting below error:
> `Traceback (most recent call last): File "test_semseg.py", line 204, in <module> main(args) File "test_semseg.py", line 133, in main batch_data[0:real_batch_size, ...] = scene_data[start_idx:end_idx, ...] TypeError: can't assign a numpy.ndarray to a Variable[CUDAType]`
> 
> I could see that because within the for loop, once the variable **batch_data** has been converted to cuda tensor in the very first iteration of for loop, I believe the same cuda tesnor is being assing with new set of block data via **scene_data[start_idx:end_idx, ...]** which is still a numpy array. Could you please confirm if my understanding about the error is correct. I can rewrite the loop accordingly.
> TIA

Thanks for your attention ^^  The bug has been fixed.
