### ISSUE TITLE
Question in ModelNetDataLoader.py

### ISSUE THREAD

**Issue by chenxiaoyu523** [yanx27/Pointnet_Pointnet2_pytorch#35]
In the classification task, the function 'farthest_point_sample()' is defined to uniformly resample the point clouds, but why the flag 'uniform' is set False?

**Comment by yanx27** [comment]
> In the classification task, the function 'farthest_point_sample()' is defined to uniformly resample the point clouds, but why the flag 'uniform' is set False?

Hi, thanks for your attention! I didn't use FPS sampling for fair comparison with PointNet++, which is randomly sample input points. However, there are some previous works like RS-CNN and DensePoint use FPS points as input, which may improve the final results, so you can just try it.
