### ISSUE TITLE
typos on the shape 

### ISSUE THREAD

**Issue by amiltonwong** [yanx27/Pointnet_Pointnet2_pytorch#36]
Hi, @yanx27 ,

Thanks for updating your code. It become more clear and concise.
One place that I found not updated is [here](https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/master/models/pointnet_util.py#L120) , the shape should be:  
new_points: sampled points data, `[B, npoint, nsample, C+D]`

**Comment by amiltonwong** [comment]
Also this [one](https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/master/models/pointnet_util.py#L119), 
the shape should be:
new_xyz: sampled points position data, `[B, npoint, C]`

**Comment by yanx27** [comment]
> Also this [one](https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/master/models/pointnet_util.py#L119),
> the shape should be:
> new_xyz: sampled points position data, `[B, npoint, C]`

Thanks for your attention again haha. Bug has been already fixed. I directly used the mark of 'sample_and_group_all' so it showed wrong shape.
