### ISSUE TITLE
question about in_channel on SA_layer_2

### ISSUE THREAD

**Issue by amiltonwong** [yanx27/Pointnet_Pointnet2_pytorch#37]
Hi, @yanx27 ,

Should the in_channel ([here](https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/master/models/pointnet2_cls_msg.py#L12)) to be : `320+3`?

**Comment by yanx27** [comment]
> Hi, @yanx27 ,
> 
> Should the in_channel ([here](https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/master/models/pointnet2_cls_msg.py#L12)) to be : `320+3`?

PointNetSetAbstractionMsg is slightly different with PointNetSetAbstraction layer, I already use in_channel + 3 within layer [here](https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/master/models/pointnet_util.py#L215).

**Comment by amiltonwong** [comment]
Thanks a lot for your clarification :)
