### ISSUE TITLE
Please clarify which version of s3dis dataset should be used

### ISSUE THREAD

**Issue by amiltonwong** [yanx27/Pointnet_Pointnet2_pytorch#38]
Hi, @yanx27 ,

Which version of s3dis dataset should be used to test your package (Pointnet_Pointnet2_pytorch)? 
Stanford3dDataset_v1.2.zip or Stanford3dDataset_v1.2_Aligned_Version.zip?

According to [indoor3d_util.py](https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/master/data_utils/indoor3d_util.py#L10), `Stanford3dDataset_v1.2_Aligned_Version` is mentioned. However, the [guide](https://github.com/yanx27/Pointnet_Pointnet2_pytorch#data-preparation-2) mentions `Stanford3dDataset_v1.2`.

Pls clarify on which version of s3dis dataset should be used.

THX!

**Comment by yanx27** [comment]
> Hi, @yanx27 ,
> 
> Which version of s3dis dataset should be used to test your package (Pointnet_Pointnet2_pytorch)?
> Stanford3dDataset_v1.2.zip or Stanford3dDataset_v1.2_Aligned_Version.zip?
> 
> According to [indoor3d_util.py](https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/master/data_utils/indoor3d_util.py#L10), `Stanford3dDataset_v1.2_Aligned_Version` is mentioned. However, the [guide](https://github.com/yanx27/Pointnet_Pointnet2_pytorch#data-preparation-2) mentions `Stanford3dDataset_v1.2`.
> 
> Pls clarify on which version of s3dis dataset should be used.
> 
> THX!

If I remember correctly, the only difference between these two data sets is that they rotate the room slightly.  You can get the same result with both datasets, but I recommend using `Stanford3dDataset_v1.2_Aligned_Version`  and I will update in README :)
