### ISSUE TITLE
Question about how to run sementic segmentation  on S3DIS dataset

### ISSUE THREAD

**Issue by LJT400** [yanx27/Pointnet_Pointnet2_pytorch#44]
Dear author, thank you for sharing the code.
When i run the train_semseg.py--model pointnet2_sem_seg --test_area 5 --log_dir pointnet2_sem_seg, 
There is an error: Given groups=1, weight of size 32 9 1 1, expected input[16, 12, 32, 1024] to have 9 channels, but got 12 channels instead.
I used the Stanford3dDataset_v1.2_Aligned_Version dataset. 
I don't know how to solve the problem and can you kindly tell me how to solve it?
thank you

**Comment by tsbiosky** [comment]
@LJT400 Hi I have the same problem, would you like to tell somthing about how to solve the problem? thanks
