### ISSUE TITLE
Data Path for Semantic Segmentation

### ISSUE THREAD

**Issue by pskugit** [yanx27/Pointnet_Pointnet2_pytorch#47]
Hi,

I noticed, that the data path for semantic segmentation is expected to be
data/s3dis/Stanford3dDataset_v1.2_Aligned_Version/
(DATA_PATH = os.path.join(ROOT_DIR, 'data','s3dis', 'Stanford3dDataset_v1.2_Aligned_Version'))

unlike the one mentioned in the Readme, which is
data/Stanford3dDataset_v1.2_Aligned_Version/

Best regards,
Philipp

**Comment by tangbohu** [comment]
That is right
