### ISSUE TITLE
it reports "cuda out of error" when testing the code with ModelNet_40_resampled using 11gb 2080ti

### ISSUE THREAD

**Issue by sharechanxd** [yanx27/Pointnet_Pointnet2_pytorch#51]
With model Pointnet_cls_msg.py, it seems that the cuda memory is not enough with the dataset.
I wonder if you use only just one gpu?

**Comment by yanx27** [comment]
Hi, @sharechanxd thank you for your attention~  You can change your batch size number through --batch_size.

`python train_cls.py --model pointnet2_cls_msg --batch_size 12`
