### ISSUE TITLE
Could not run 'aten::conj.out' with arguments from the 'CUDATensorId' backend.

### ISSUE THREAD

**Issue by maptastic** [yanx27/Pointnet_Pointnet2_pytorch#55]
Getting the following error in the feature transform regularizer for train_sem_seg.py. 

RuntimeError: Could not run 'aten::conj.out' with arguments from the 'CUDATensorId' backend. 'aten::conj.out' is only available for these backends: [CPUTensorId, VariableTensorId].

Any suggestions for how to fix?

**Comment by malcolmyanguci** [comment]
I got same problem. I believe you are using model 'pointnet_sem_seg'. I found that the torch.norm() somehow does not work very well if the input data has been loaded by .cuda(), so I solve it by .cpu() and then load by .cuda() like this:
`def feature_transform_regularizer(trans):
    d = trans.size()[1]
    I = torch.eye(d)[None, :, :]
    if trans.is_cuda:
        I = I.cuda()
    my_tensor = torch.bmm(trans, trans.transpose(2, 1) - I).cpu()
    my_tensor = torch.norm(my_tensor, dim=(1, 2))
    loss = torch.mean(my_tensor).cuda()
    return loss`

**Comment by phy12321** [comment]
I met the same problem. I found it is a issue caused by pytorch1.4, and was fixed in pytorch1.5

**Comment by yanx27** [comment]
Please test with different Torch version~
