### ISSUE TITLE
Excuse me,what is modelnet40 pointcloud type? Is that PointXYZINormal?does it affect to pointnet Classification?

### ISSUE THREAD

**Issue by francoe0088** [yanx27/Pointnet_Pointnet2_pytorch#56]
I downloaded data modelnet40 from this github,but its not just .off type,want to know this pointcloud  type and does it affect to pointnet Classification ?

Is that PointXYZINormal ?
PointXYZINormal - float x, y, z, intensity, normal[3], curvature;

**Comment by yanx27** [comment]
@francoe0088 We use pre-processed ModelNet40 dataset, which is provided by [PointNet++](https://github.com/charlesq34/pointnet2/tree/master/data).

**Comment by francoe0088** [comment]
@yanx27 Thanks your respond！
