### ISSUE TITLE
Do Normals also need to be transformed by T-Net?

### ISSUE THREAD

**Issue by hansen7** [yanx27/Pointnet_Pointnet2_pytorch#57]
Hi, @yanx27, thanks for your contribution, it helps me a lot!

I have a question on the T-Net when PointNet model also takes normal as the input, recall the code:

https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/2d08fa40635cc5eafd14d19d18e3dc646171910d/models/pointnet.py#L107-L111

It only apply T-Net transformation on the coordinates but not the normals, however, the input for solving T-Net includes the normals:

https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/2d08fa40635cc5eafd14d19d18e3dc646171910d/models/pointnet.py#L10-L13
https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/2d08fa40635cc5eafd14d19d18e3dc646171910d/models/pointnet.py#L88-L91
https://github.com/yanx27/Pointnet_Pointnet2_pytorch/blob/2d08fa40635cc5eafd14d19d18e3dc646171910d/models/pointnet_cls.py#L9-L13

In my understanding, the T-Net can be pictures as the some rotation alignment for rigid objects, therefore, **it should apply both on the coordinates and the normals**, right?

**Comment by AkashPatel95** [comment]
If I am not wrong, Pointnet was designed to work with point co-ordinates only. PointNet++ has supports for normals and additional features.

**Comment by hansen7** [comment]
thanks for the clarification!
