### ISSUE TITLE
S3DIS eval result error

### ISSUE THREAD

**Issue by fullcyxuc** [yanx27/Pointnet_Pointnet2_pytorch#63]
It seems that the IoU of the 4th class is always near to 0, whatever the 4th class is. Just like this:
------- IoU --------
class ceiling        weight: 0.092, IoU: 0.840 
class floor          weight: 0.201, IoU: 0.973 
class wall           weight: 0.166, IoU: 0.726 
class beam           weight: 0.274, IoU: 0.000         <-----
class column         weight: 0.000, IoU: 0.052 
class window         weight: 0.019, IoU: 0.410 
class door           weight: 0.034, IoU: 0.163 
class table          weight: 0.028, IoU: 0.512 
class chair          weight: 0.039, IoU: 0.453 
class sofa           weight: 0.018, IoU: 0.081 
class bookcase       weight: 0.003, IoU: 0.506 
class board          weight: 0.114, IoU: 0.267 
class clutter        weight: 0.011, IoU: 0.306 

is it any problems in the train_semseg.py file or the data preprocess?

**Comment by jasonwjw** [comment]
Hi, sir, did you figure it out?
