### ISSUE TITLE
cannot load test dataset for semantic segmentation with pointnet2 because of the size

### ISSUE THREAD

**Issue by kaixin-bai** [yanx27/Pointnet_Pointnet2_pytorch#66]
while using `python train_semseg.py --model pointnet2_sem_seg --test_area 5 --log_dir pointnet2_sem_seg` to train semantic segmentation, the `TRAIN_DATASET` cost over 15G on CPU, and the program is killed while starting to load test data. How to fix this?

**Comment by lyy-1997-hub** [comment]
maybe you can decrease the value of batch_size = 16 or 8 or 4 or 2 or 1 in train_semseg.py

**Comment by Rainbow923** [comment]
I have the same problem, please, have you sloved the problem ?  I tryed batch_size=2,but also have the problem.

**Comment by umarkhancodes** [comment]
facing the same problem , 
has anyone tried training on colab ?

**Comment by WangZhouTao** [comment]
@kaixin-bai are you slove this problem? Hope your reply.
