### ISSUE TITLE
One question about the implementation orthogonal matrix 

### ISSUE THREAD

**Issue by MaybeOjbk** [yanx27/Pointnet_Pointnet2_pytorch#67]
your code 
![图片](https://user-images.githubusercontent.com/38483419/89431419-7ce75380-d772-11ea-9a4a-12bc1cf9be24.png)
which means || A(A.T- I ) || . Does it equals to || I - AA.T || ?

**Comment by jiu-jian-xian** [comment]
我觉得这里应该是写错了吧。

**Comment by yanx27** [comment]
already fixed
