### ISSUE TITLE
How much of your GPU memory usage of train？

### ISSUE THREAD

**Issue by hualin95** [yanx27/Pointnet_Pointnet2_pytorch#7]

**Comment by yanx27** [comment]
> _No description provided._

12G

**Comment by hualin95** [comment]
Thank you for your answer. I have runned your code and got an error of insufficient memory. Now, it seems that my guess is correct. Maybe you can improve your train code to decrease the GPU memory, I have combined your net code with my train file, and it consumed 2G GPU memory during train.

**Comment by yanx27** [comment]
> Thank you for your answer. I have runned your code and got an error of insufficient memory. Now, it seems that my guess is correct. Maybe you can improve your train code to decrease the GPU memory, I have combined your net code with my train file, and it consumed 2G GPU memory during train.

You can set small batchsize number if you have not enough GPU memory, try python XX.py --batchsize 12(or smaller)

**Comment by tangbohu** [comment]
> Thank you for your answer. I have runned your code and got an error of insufficient memory. Now, it seems that my guess is correct. Maybe you can improve your train code to decrease the GPU memory, I have combined your net code with my train file, and it consumed 2G GPU memory during train.

Hi! how did you decrease the gpu memory?

**Comment by Ayush1651999** [comment]
@tangbohu , as @yanx27 mentioned, reduce the batch_size. It will reduce the memory used. Hope this helps

**Comment by sun300020** [comment]
> Thank you for your answer. I have runned your code and got an error of insufficient memory. Now, it seems that my guess is correct. Maybe you can improve your train code to decrease the GPU memory, I have combined your net code with my train file, and it consumed 2G GPU memory during train.

Hello, would you be willing to tell me how to control the gpu memory to 2
g or less?
