### ISSUE TITLE
Does the input data have to be in n*6 form ?

### ISSUE THREAD

**Issue by xlj199** [yanx27/Pointnet_Pointnet2_pytorch#70]
I'm doing the pointnet classification section.Use the data(modelnet40_normal_resampled) set you provided and the code works fine.However,I input my own dataset(n*3) and this error occurred.
"RuntimeError: Given groups=1, weight of size [32, 6, 1, 1], expected input[8, 3, 16, 512] to have 6 channels, but got 3 channels instead"
I'm using a neural network is pointnet2_cls_msg.My guess is that the format of the data doesn't match the network.
If this is the case, please provide the appropriate n*3 format of the neural network or prompt

**Comment by yanx27** [comment]
if you use `--use_normals`, it will set input dimension equal to 6:)
