### ISSUE TITLE
A question regarding shapenetcore_partanno_segmentation data

### ISSUE THREAD

**Issue by edshkim98** [yanx27/Pointnet_Pointnet2_pytorch#72]
Hi, I am trying to run the part segmentation model and I found out that the data consists of 6 columns with a label column.
I know that the first 3 columns are for coordinates of nx, ny and nz where n indicates normalized, but can someone please explain to me what the rest 3 columns are?
For example in the first line of 157936971ef9b6bb858b20d410ebdb99.txt file,
-0.253770 -0.041050 -0.000220 -0.999500 0.026250 -0.014680 0.000000 ->normal_x ,normal_y, normal_z,  ?, ? , ?,  label
and I am not sure about those question marked values (-0.999500 0.026250 -0.014680) are.
Thank you in advance for the help.

**Comment by littlelittlebin** [comment]
x, y, z, normal_x ,normal_y, normal_z, label

**Comment by ruchaa01** [comment]
@littlelittlebin : Thank you for your reply. I am trying to make my own dataset. For that, can you help me understand how to calculate normal_x, normal_y and normal_z in this case? Thank you so much.

**Comment by edshkim98** [comment]
@ruchaa01 I think it's just normalizing into a unit sphere.

**Comment by littlelittlebin** [comment]
> @littlelittlebin : Thank you for your reply. I am trying to make my own dataset. For that, can you help me understand how to calculate normal_x, normal_y and normal_z in this case? Thank you so much.

you can try to use ball query firstly, then pca, google search may help you.
