### ISSUE TITLE
classification error: ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512])

### ISSUE THREAD

**Issue by johnjwatson** [yanx27/Pointnet_Pointnet2_pytorch#75]
I am trying to run the repo via:

    python train_cls.py --model pointnet2_cls_msg --normal --log_dir pointnet2_cls_msg --batch_size 2 --epoch 5

and I get:

Namespace(batch_size=2, decay_rate=0.0001, epoch=5, gpu='0', learning_rate=0.001, log_dir='pointnet2_cls_msg', model='pointnet2_cls_msg', normal=True, num_point=1024, optimizer='Adam')
Load dataset ...
The size of train data is 9843
The size of test data is 2468
No existing model, starting training from scratch...
Epoch 1 (1/5):
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 4921/4922 [27:59<00:00,  2.93it/s]

Traceback (most recent call last):
  File "train_cls.py", line 209, in <module>
    main(args)
  File "train_cls.py", line 166, in main
    pred, trans_feat = classifier(points)
  File "home/dir/pointnetpp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "home/dir/pointnetpp/etc/bmark/models/pointnet2_cls_msg.py", line 33, in forward
    x = self.drop1(F.relu(self.bn1(self.fc1(x))))
  File "home/dir/pointnetpp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "home/dir/pointnetpp/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "home/dir/pointnetpp/lib/python3.7/site-packages/torch/nn/functional.py", line 2012, in batch_norm
    _verify_batch_size(input.size())
  File "home/dir/pointnetpp/lib/python3.7/site-packages/torch/nn/functional.py", line 1995, in _verify_batch_size
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512])

Why is this?

br,

**Comment by mazhenyuwin** [comment]
HI, I meet the same problem. Have u solved this problem??

**Comment by jin111** [comment]
I met the same problem, and  I cut some training data to make the training data num % batchsize == 0 , then it goes ok.

**Comment by zhenzhen11414** [comment]
> 使

作者给的有40个数据集，我的batch_size=2,跑的时候报同样的错，要怎么改呢？

**Comment by azhuantou** [comment]
I met the same. I think it is no need to use bn here, cuz bn is somehow channel-wise normalization, thist require more than 1 value per channel. So I change the code in pointnet2_cls_msg.py 
`       x = self.drop1(F.relu(self.bn1(self.fc1(x))))
        x = self.drop2(F.relu(self.bn2(self.fc2(x))))`
to
 `        x = self.drop1(F.relu(self.fc1(x)))
        x = self.drop2(F.relu(self.fc2(x)))`
And it works for me.
