### ISSUE TITLE
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 512])

### ISSUE THREAD

**Issue by zhenzhen11414** [yanx27/Pointnet_Pointnet2_pytorch#78]
![P HX} 0HMC~DA_J2 X 4IE3](https://user-images.githubusercontent.com/48001378/96978894-76869d80-1551-11eb-85bf-dd9d130577ca.png)
![U6B~%DCVXN}){JPB~~4{9KB](https://user-images.githubusercontent.com/48001378/96978900-77b7ca80-1551-11eb-9f7a-78e4aa79b774.png)

200个epoch，训练了1个epoch就停了，怎么解决？

**Comment by yanx27** [comment]
Adding `drop_last=True`  in dataloader :)
