### ISSUE TITLE
About the voting code

### ISSUE THREAD

**Issue by ycjing** [yanx27/Pointnet_Pointnet2_pytorch#81]
Hi @yanx27 

Thank you for this nice code! I have a quick question. I found that during inference, even if given the same random seed, model and input data, the results of different forward passes are different. 

Is it the reason why the code uses the voting action to average the results of several forward passes? Where does this randomness come from? I think that each forward pass should give the same result with the same input data.

Thank you! Wish you all the best!

Best,
Yongcheng

**Comment by yanx27** [comment]
@ycjing Hi, sorry for late response. We use voting test just following the official PointNet++. If you don't want it, just set `num_vote` equal to 1:)
