### ISSUE TITLE
Why calculate the 'labelweights' used in the function 'add_vote'

### ISSUE THREAD

**Issue by Daizheng-z** [yanx27/Pointnet_Pointnet2_pytorch#86]
I want to know why labelweights are calculated like this：

self.labelweights = np.power(np.amax(labelweights) / labelweights, 1 / 3.0)

If a label does not exist, its labelweight will be calculated as inf, so that this condition in the function add_vote must be true：

def add_vote(vote_label_pool, point_idx, pred_label, weight):
    B = pred_label.shape[0]
    N = pred_label.shape[1]
    for b in range(B):
        for n in range(N):
            print(weight[b,n])
            <<<<if weight[b,n]:>>>>
                vote_label_pool[int(point_idx[b, n]), int(pred_label[b, n])] += 1
    return vote_label_pool

What is the effect of this calculation?

**Comment by yanx27** [comment]
Hi, thx~ The bug is already fixed and the segmentation results are improved better.
