### ISSUE TITLE
Confused on the dimension of alignment ModelNet 

### ISSUE THREAD

**Issue by Ariellsc** [yanx27/Pointnet_Pointnet2_pytorch#87]
![image](https://user-images.githubusercontent.com/31057694/102162279-db140800-3ec3-11eb-9f60-e740645d74ad.png

with respect to the input data during forward,   B, D, N = x.size() 
I want to know why the dimension of the  alignment ModelNet dataset you provided is 6, namely,  why D is 6 ?

**Comment by lykius** [comment]
I believe it's (x, y, z, nx, ny, nz), where (nx, ny, nz) represent the normal.

**Comment by yanx27** [comment]
@Ariellsc It's the normal vector of each point, please refer to the official [PointNet++](https://github.com/charlesq34/pointnet2).
