### ISSUE TITLE
PointNet2_ssg (Pytorch)	53.2

### ISSUE THREAD

**Issue by suyunzzz** [yanx27/Pointnet_Pointnet2_pytorch#88]
Hello,thanks for the project.
i want to know how do you get this miou in S3DIS, in traning?or in test?
i get miou in training is 52.81,in test is only 43.5517?

**Comment by yanx27** [comment]
Hi @suyunzzz , the results of 52.81 is achieved on sub-point of dataset of PointNet. Now we train and test on raw point cloud without sampling. I removed the results on README to prevent misunderstand.

**Comment by yanx27** [comment]
By the way, the [issue 86](https://github.com/yanx27/Pointnet_Pointnet2_pytorch/issues/86) hampers the performance, you can test results again.

**Comment by yanx27** [comment]
Hi, @suyunzzz , I provided pretrained models, please check in the new README.
