### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by zeinaabuaisheh** [yanx27/Pointnet_Pointnet2_pytorch#9]
Hello,

Thanks a lot for the accessible code. 
Can you please share with us the pretrained model for the classification test on ModelNet?

Thanks a lot

**Comment by MaxChanger** [comment]
@zeinaabuaisheh  Hello, did you train this network and save a pretrained model ?
Thanks.

**Comment by YiruS** [comment]
Same here. Is there any available pretrained model online?

**Comment by MaxChanger** [comment]
> Same here. Is there any available pretrained model online?
@YiruS This repository is not official and I haven't found pertrained model either, but you can prepare a data set in HDF5 format by yourself. It's not very difficult to train.

**Comment by yanx27** [comment]
Already provided pretrain models for semantic segmentation.
