### ISSUE TITLE
can not find the eval.txt

### ISSUE THREAD

**Issue by li-pen** [yanx27/Pointnet_Pointnet2_pytorch#92]
Hello,thanks for the project.
i want to know how to get the eval.txt which i need when i run the test_cls

**Comment by yanx27** [comment]
@li-pen Did you use accurate `log_dir`?

**Comment by li-pen** [comment]
Thank you very much! I learned

**Comment by qilijin** [comment]
我不太理解如何准确使用log_dir  请教一下  谢谢

**Comment by 13717630148** [comment]
> 我不太理解如何准确使用log_dir 请教一下 谢谢

同问解决了吗

**Comment by WanderingSta** [comment]
怎么解决的？
