### ISSUE TITLE
When using PointNet for sem_seg, the dimension of data set is 9, while PointNet requires 6.

### ISSUE THREAD

**Issue by lllmmmwww** [yanx27/Pointnet_Pointnet2_pytorch#94]
Hi，
Thank you for your work! I have a question for you.
When I using PointNet for sem_seg, the dimension of data set is 9, while PointNet requires 6.So how do we solve it？

Look forward to your reply!

**Comment by yanx27** [comment]
Already fixed and updated :) See [issue 95](https://github.com/yanx27/Pointnet_Pointnet2_pytorch/issues/95).

**Comment by lllmmmwww** [comment]
> Already fixed and updated :) See [issue 95](https://github.com/yanx27/Pointnet_Pointnet2_pytorch/issues/95).
Thank you very much!
