### ISSUE TITLE
Rotation and Jitter in Data Augmentation

### ISSUE THREAD

**Issue by sheshap** [yanx27/Pointnet_Pointnet2_pytorch#96]
Hi, Thanks for the PyTorch implementation with higher accuracies.

I am wondering if the improvement in accuracy is due to not augmenting the data with rotation, and jitter?

I see from your train_cls.py script that you are doing random point dropout, random scale, and shifting of points.

            points = provider.random_point_dropout(points)
            points[:,:, 0:3] = provider.random_scale_point_cloud(points[:,:, 0:3])
            points[:,:, 0:3] = provider.shift_point_cloud(points[:,:, 0:3])

However, PointNet++ does rotation and jitter in their augmentation.
Please let us know if these two augmentations are done.

Thanks in advance

**Comment by yanx27** [comment]
@sheshap Hi, thanks for your attention. According to my experiment, rotation and jitter did hamper the performance. Since the ModelNet40 provided by PointNet++ is already aligned, there is no need to rotation for data augmentation, which will difficult the task.
