### ISSUE TITLE
pointnet_segtrain question

### ISSUE THREAD

**Issue by cystal-lili** [yanx27/Pointnet_Pointnet2_pytorch#98]
EOFError: Ran out of input
运行的时候出现这个问题，数据没有问题，是什么原因呢

**Comment by yanx27** [comment]
@cystal-lili Can you load data successfully?

**Comment by cystal-lili** [comment]
可以&nbsp; &nbsp;也可以读到数据 但是我用的是windows系统 现在换一下乌班图的试一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yanx27/Pointnet_Pointnet2_pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月6日(星期二) 中午12:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yanx27/Pointnet_Pointnet2_pytorch] pointnet_segtrain question (#98)





 
@cystal-lili Can you load data successfully?

**Comment by cystal-lili** [comment]
train_segseg.py可以运行&nbsp; test的时候报一下错误&nbsp;&nbsp;
usage:&nbsp;Model&nbsp;[-h]&nbsp;[--batch_size&nbsp;BATCH_SIZE]&nbsp;[--gpu&nbsp;GPU]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[--num_point&nbsp;NUM_POINT]&nbsp;--log_dir&nbsp;LOG_DIR&nbsp;[--visual]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[--test_area&nbsp;TEST_AREA]&nbsp;[--num_votes&nbsp;NUM_VOTES]
Model:&nbsp;error:&nbsp;the&nbsp;following&nbsp;arguments&nbsp;are&nbsp;required:&nbsp;--log_dir

什么原因呢&nbsp; &nbsp;
还有一个问题就是为什么在测试的时候用ScannetDataset的数据呢
from&nbsp;data_utils.S3DISDataLoader&nbsp;import&nbsp;ScannetDatasetWholeScene
非常感谢
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yanx27/Pointnet_Pointnet2_pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月6日(星期二) 中午12:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yanx27/Pointnet_Pointnet2_pytorch] pointnet_segtrain question (#98)





 
@cystal-lili Can you load data successfully?

**Comment by yanx27** [comment]
@cystal-lili You need specify `--log_dir` with your training direction.

**Comment by cystal-lili** [comment]
非常感谢&nbsp; 可以运行了&nbsp; 但是不理解为什么在测试的时候用ScannetDataset的数据呢
from data_utils.S3DISDataLoader import ScannetDatasetWholeScene





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yanx27/Pointnet_Pointnet2_pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月7日(星期三) 中午12:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yanx27/Pointnet_Pointnet2_pytorch] pointnet_segtrain question (#98)





 
@cystal-lili You need specify --log_dir with your training direction.

**Comment by yanx27** [comment]
We chop original scenes into 1x1 cubes in training phase, while we need inference the whole scene in testing.

**Comment by cystal-lili** [comment]
一共6六块数据，第五块数据作为测试数据，其他的数据作为训练数据进行处理，这样理解对吗？
因为我们需要的到第五块总体的精度


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yanx27/Pointnet_Pointnet2_pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月8日(星期四) 下午5:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yanx27/Pointnet_Pointnet2_pytorch] pointnet_segtrain question (#98)





 
We chop original scenes into 1x1 cubes in training phase, while we need inference the whole scene in testing.

**Comment by yanx27** [comment]
Yes, there are total six areas in the building. We trained on 1,2,3,4,6 areas and test on the 5-th. This strategy follows the setting of PointNet.
